Main:
  pickle: .\picklefiles
  run: .\runfiles
  graphimg: .\graph_images
  csv: .\csvfiles
  checkpoint: .\checkpoint
  data: D:\Entity Aspect Linking\data\entity-aspect-linking-2020\collection
  result: .\results
DNN:
  Train:
    epochs: 60
    lr: 0.001
    weight_decay: 1e-4
    train_ratio: 0.8
    val_ratio: 0.2
    batch_size: 128

  Test:
    batch_size: 256

GNN:
  Train:
    epochs: 100
    lr: 3e-5
    weight_decay: 1e-4
    batch_size: 128
    disjoint_train_ratio: 0
    negative_sampling_ratio: 5

  Test:
    batch_size: 128
    disjoint_train_ratio: 0
    negative_sampling_ratio: 5

FinetunedGNN:
  Train:
    epochs: 60
    lr: 2e-5
    weight_decay: 0.0001
    batch_size: 256
    disjoint_train_ratio: 0.999
    negative_sampling_ratio: 1



