Main:
  pickle: ./picklefiles
  run: ./runfiles
  graphimg: ./graph_images
  csv: ./csvfiles
  checkpoint: ./checkpoint
DNN:
  Train:
    epochs: 60
    lr: 0.1
    weight_decay: 0.01
    batch_size: 128

  Test:
    batch_size: 1



